### ISSUE TITLE
How do I trigger in-app update notifications?

### ISSUE THREAD

**Issue by momo-the-monster** [bitstadium/HockeySDK-Unity-Android#10]
I've got a Unity Android application with HockeyApp SDK integrated. 
I've set the package name and the App ID on the GameObject, and checked the 'Update Manager' box.
I've installed HockeyApp on two of my tablets, added the devices, and installed a version of the application.
Then I create a new version of the application and upload it to HockeyApp.
The tablets each receive an email notification about the new version, but no in-app or system-level notification.
How can I trigger notifications or force upgrades?

**Comment by chrwend** [comment]
Did you increase the Bundle Version Code in the build settings by 1 before uploading it to HockeyApp?

**Comment by momo-the-monster** [comment]
I incremented my version number each time, but not my bundle version code.
Is that necessary to trigger the update?

**Comment by lumaxis** [comment]
@momo-the-monster HockeyApp sorts build by bundle version code as the version number is only a visual/marketing representation but does normally not uniquely identify a binary.
To make sure both HockeyApp and eventually for example Google Play work properly, please always increase the version code with every build of your app.

**Comment by momo-the-monster** [comment]
Aha! Thanks, Lumaxis. I see that it checks for updates on startup - how can I trigger a regular update check manually? I'm hoping there's something in net.hockeyapp.unity.HockeyUnityPlugin but I can't seem to dig into it at all or find documentation on the methods within.

**Comment by chrwend** [comment]
@momo-the-monster, unfortunately the wrapper doesn't provide this functionality, yet.

**Comment by momo-the-monster** [comment]
Oh, bummer! The whole reason for us integrating HockeySDK is to auto-update our app. Is there any other way to accomplish this?

**Comment by chrwend** [comment]
Of course on solution is make contributions to the project =) For now, will put that one the list for the next update,

**Comment by momo-the-monster** [comment]
Wish I could, but my Java/Android skills are not up to par. Thanks for your feedback and help.

**Comment by chrwend** [comment]
@momo-the-monster the most recent version of the HockeySDK for Unity (1.2.0) exposes a new method, which can be used to explicitly trigger update checks.
