### ISSUE TITLE
Provide a lightweight version of the Hockeyapp SDK that doesn't include any dependent Library

### ISSUE THREAD

**Issue by andylmtang** [bitstadium/HockeySDK-Unity-Android#12]
We are having an issue with duplicated google libraries in our codebase and we are not able to remove these duplication because the Hockeyapp SDK is now a single file in aar format. So we are wondering if it would be possible for Hockeyapp to ship a lightweight SDK that doesn't include any dependent library so that we can add them in manually. Thanks

**Comment by andylmtang** [comment]
Any Update on this?

**Comment by chrwend** [comment]
Hi @andylmtang,

> We are having an issue with duplicated google libraries in our codebase?
Which libraries are you referring to?

> So we are wondering if it would be possible for Hockeyapp to ship a lightweight SDK that doesn't include any dependent library 
Sounds good. 

For now, you can just clone the repo and rebuild the `HockeyAppUnityPlugin`
 project.

Chris

**Comment by TroubleMakerBen** [comment]
Just to clarify: the Unity SDK for HockeyApp is a simple wrapper around our native Android SDK which doesn't have dependencies on stuff like e.g. Play Services, etc or other 3rd party libs. Are you sure HockeyApp is at the root of the issue?

**Comment by TroubleMakerBen** [comment]
Sending a quick ping before I close this issue!
