### ISSUE TITLE
Consider changing the name of the folder 'Plugin' to 'Plugins'.

### ISSUE THREAD

**Issue by richardelms** [bitstadium/HockeySDK-Unity-Android#14]
Right now when you import the sdk it gets added under assets into a folder just named 'Plugin'.

If you renamed it to 'Plugins' then unity would automatically add the sdk to the often already existent Plugins folder which is the preferred location for 3rd party code in unity.

**Comment by chrwend** [comment]
@richardelms Sure, I'm going to add it in the upcoming release. Thank you! :+1:

**Comment by TroubleMakerBen** [comment]
We've changed this to Plugin**S**.

Closing the issue.
