### ISSUE TITLE
Check for custom server string default value

### ISSUE THREAD

**Issue by richardFunrock** [bitstadium/HockeySDK-Unity-Android#15]
Leaving the customUrl field with it's default value causes error reporting to not work due to malformed URL errors. Right now you have to make it an empty string. This is easy to over look. 

I would expect the default value to also be checked for.

Maybe either add a bool checkbox for custom server usage, or improve the (string.length > 0) check to also look for the default value of the customUrl string

**Comment by TroubleMakerBen** [comment]
Hey @richardFunrock 

thx for reporting this. We'll see what we can do.

**Comment by TroubleMakerBen** [comment]
We've fixed this in 5.0.0 =)

Thx for reporting this and for using HockeyApp!
