### ISSUE TITLE
Exceptions/crashes not getting logged/uploaded to HockeyApp (plugin not properly integrated?)

### ISSUE THREAD

**Issue by atraver** [bitstadium/HockeySDK-Unity-Android#32]
I recently upgraded the HockeyApp Unity SDK in our Android build to v5.0.1 and haven't been able to get exception/crash logging working on our production build. The development build handles this fine, but when we build the production version of our game and upload a copy to HockeyApp, nothing is getting logged. I've looked through the merged `AndroidManifest.xml` file and they look very similar. The thing that makes me think the SDK isn't properly integrated is the message on the "Crashes" tab for versions of our production build:

![image](https://user-images.githubusercontent.com/6304/34371115-2eaba014-ea7f-11e7-9fdf-c46f52a75bb0.png)

The development build does not contain the message on integrating the SDK, so maybe something is wrong when building the APK? I've verified the HockeyApp app and package IDs in Unity, and exporting as a Gradle project shows that both the `HockeySDK-5.0.4.aar` and `hockeysdk-unity-5.0.1.aar` files exist and are getting compiled.

Here's my merged manifest: [AndroidManifest.txt](https://github.com/bitstadium/HockeySDK-Unity-Android/files/1588340/AndroidManifest.txt)

Any ideas?

**Comment by MatkovIvan** [comment]
Hi Adam,

To figure out what is happening, could you please show me an application log from `logcat` or check that the SDK initialized by yourself? Are there any errors?

Also, please note: crashes will be sent only the next time you start the application.

Best,
Ivan

**Comment by atraver** [comment]
Thanks for the note, Ivan.

Here are my logcat logs when starting the game: [logcat.log](https://github.com/bitstadium/HockeySDK-Unity-Android/files/1589859/logcat.log) (note that the logs after the lines in the file occur once the scene has already been loaded, so we assume the `HockeyAppAndroid.cs` file has already gone through its `Awake()` method to initialize the integration). There is no information (errors or otherwise) showing up in logcat related to HockeyApp.

We previously had version 1.1.6 of the HockeyApp plugin integrated into our game and were receiving crashes, so this is out of the ordinary for us.

**Comment by MatkovIvan** [comment]
This happens only on your main application or are you able to reproduce the issue on sample/empty app? During my tests crashes are sent fine, so reproduction sample would be extremely helpful.
Also, the following things may be useful for investigating the issue:
- Other SDK functions are still working (metrics, feedback etc)?
- There are any outgoing HTTP requests from the SDK (you can watch this through a debugging proxy. Personally, I use Fiddler)?
- Does disabling Proguard change anything?

**Comment by atraver** [comment]
It looks like metrics are working properly (we don't enable feedback in production builds):

![image](https://user-images.githubusercontent.com/6304/34426997-a1aa09de-ebf1-11e7-9938-92936e970941.png)

The weird thing is that we have two separate apps in HockeyApp: a development build and a production build. Each has a different package ID (e.g., com.ourcompany.ourgame.dev and com.ourcompany.ourgame). The development build, using the same HockeyApp plugin, is able to report crashes and do the update workflow just fine. It's just the production build that's falling down. Really, the only difference between the two is the different package ID (and we change the HockeyApp App ID in the Game Object with the `HockeyAppAndroid` script, too), and the fact that we set the "Development Build" checkbox in the player settings for the development build only.

I'll try disabling Proguard and monitoring HTTP traffic, but the fact that the development build is presumably using it (since I've never disabled it in that build previously) makes me think those might not be related.

**Comment by atraver** [comment]
Weird, as of this morning exceptions are rolling in. Obviously something changed, I just don't know what! Either way, thanks for sticking through it with me.

**Comment by TroubleMakerBen** [comment]
Hi @atraver,
I'm glad this is working again, although I'd really like to know what went wrong.
Anyway, if anything comes up again, please get in touch.

Happy 2018 and thank you for using HockeyApp!
Benjamin
