### ISSUE TITLE
Building with ProGuard causes java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by atraver** [bitstadium/HockeySDK-Unity-Android#35]
Hi, guys.

On Debug builds of our game, we're not using ProGuard. However, we use it on Release builds and I'm noticing in our logs that the HockeyApp classes cannot be found when doing so:

```
02-05 14:01:18.598 29095 29111 E Unity   : AndroidJavaException: java.lang.ClassNotFoundException: net.hockeyapp.unity.HockeyUnityPlugin
02-05 14:01:18.598 29095 29111 E Unity   : java.lang.ClassNotFoundException: net.hockeyapp.unity.HockeyUnityPlugin
02-05 14:01:18.598 29095 29111 E Unity   : 	at java.lang.Class.classForName(Native Method)
02-05 14:01:18.598 29095 29111 E Unity   : 	at java.lang.Class.forName(Class.java:324)
02-05 14:01:18.598 29095 29111 E Unity   : 	at java.lang.Class.forName(Class.java:285)
02-05 14:01:18.598 29095 29111 E Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
02-05 14:01:18.598 29095 29111 E Unity   : 	at com.unity3d.player.UnityPlayer.c(Unknown Source)
02-05 14:01:18.598 29095 29111 E Unity   : 	at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
02-05 14:01:18.598 29095 29111 E Unity   : 	at android.os.Handler.dispatchMessage(Handler.java:98)
02-05 14:01:18.598 29095 29111 E Unity   : 	at android.os.Looper.loop(Looper.java:158)
02-05 14:01:18.598 29095 29111 E Unity   : 	at com.unity3d.player.UnityPlayer$c.run(Unknown Source)
02-05 14:01:18.598 29095 29111 E Unity   : Caused by: java.lang.ClassNotFoundException: Didn't find class "net.hockeyapp.unity.HockeyUnityPlugin" on path: DexPathList[[zip file "/data/app/com.mycompany.mygame-2/base.apk"],nativeLibraryDirectories=[/data/app/com.mycompany.mygame-2/lib/arm, /data/app/com.mycompany.mygame-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
02-05 14:01:18.598 29095 29111 E Unity   : 	at dalvik.syst
```
Unity (as recently as 2017.2.1p2, at least) provides a way to send custom commands to ProGuard via a `Assets/Plugins/Android/proguard-user.txt` file, which I'm using in order to get around warnings. It looks like this:

```
-keep class com.unity.purchasing.** { *; }
-keep class net.hockeyapp.android.** { *; }
-dontwarn com.unity.purchasing.**
-dontwarn net.hockeyapp.android.**
```
I had to add the `dontwarn` flags because Unity's build process would error-out without them ([and Unity's developers have acknowledged](https://forum.unity.com/threads/proguard-content.498657/#post-3381447)). However, even with the `keep` flags, it seems as though the HockeyApp classes are getting stripped?

**Comment by TroubleMakerBen** [comment]
Hey @atraver,

Thx for reporting this. We'll take a look at this.

Best,
Benjamin

**Comment by MatkovIvan** [comment]
Hi,

This class doesn't match current wildcards and will be stripped during build.
This line should solve it:
`-keep class net.hockeyapp.unity.HockeyUnityPlugin { *; }`
Let me know if it doesn't work for you.

Best,
Ivan

**Comment by atraver** [comment]
Geez, you're right. It's right there in the log! Sorry about that, my brain was fried from looking at all these classes. I'll take a look and see if it fixes things.

**Comment by TroubleMakerBen** [comment]
Any luck with this @atraver ?

**Comment by atraver** [comment]
Honestly, I haven't had any time to delve into this. Let's go ahead and close it and if I run into it again I'll revisit it.

**Comment by TroubleMakerBen** [comment]
Okay! Thx @atraver.
