### ISSUE TITLE
exceptionLogging is used to check whether we should send logs

### ISSUE THREAD

**Issue by bhvr-vpaquette** [bitstadium/HockeySDK-Unity-Android#36]
exceptionLogging isn't meant to be used as a condition for whether we should send the logs on awake. At least not according to the docs.

**Comment by guperrot** [comment]
Sorry, I didn't understand the question. Please add more details about what you are trying to do using the SDK.

**Comment by bhvr-vpaquette** [comment]
In the awake function, if the exceptionLogging flag is set to false, the SendLogs function won't be called. According to the docs, exceptionLogging is meant to be used if we want to track native exceptions as well as crashes.

Btw, the same thing is true for the ios SDK.

**Comment by TroubleMakerBen** [comment]
Hey @bhvr-vpaquette,

Thanks for getting in touch. We have a really hard time following your thoughts here. Can you please be more verbose in your descriptions?

I'm thinking you have an issue with [this line](https://github.com/bitstadium/HockeySDK-Unity-Android/blob/57a113e80176fe437eed685ecc64c2718056d780/ExampleGame/Assets/HockeyAppUnityAndroid/HockeyAppUnity-Scripts/HockeyAppAndroid.cs#L62) and the way the `Readme.md` is phrased.
If this is the case, are you referring to this sentence of the readme:
`Exception Logging - by checking this option you will get more precise information about exceptions in your Unity scripts`?

We are happy to make this more precise so it's clear that `Exception Logging` needs to be enabled to report non-fatal c# exceptions.

**Comment by bhvr-vpaquette** [comment]
Yes, that's the line. However, you'll notice that if the variable is set to false, not only will the SDK stop reporting non fatal exceptions, it will also stop sending crash reports all together since the call to SendLogs is only made from that part of the code.

**Comment by guperrot** [comment]
Hi, native (Java) crash reports are managed by the underlying Android SDK which is hosted in its own repository. Unity SDK is a wrapper on the native SDKs. This flags controls only C# exception reporting (not causing crash), while crashes are caused by Java exceptions on Android.

**Comment by bhvr-vpaquette** [comment]
Oh so the SendLogs behaviour is duplicated on the native side? Why isn't the Unity script calling the native code for Sending Logs?

Thanks for the info :)
