### ISSUE TITLE
Android build stops in Unity, error CS0103, missing methods/names

### ISSUE THREAD

**Issue by bikush** [bitstadium/HockeySDK-Unity-Android#7]
Methods in question are HockeyApp_GetSdkVersion and HockeyApp_GetSdkName.
ExampleGame/Assets/HockeyAppUnityAndroid/HockeyAppUnity-Scripts/HockeyAppAndroid.cs has correctly named methods.

Solution:
Remove "HockeyApp_" prefix in method SendLogs in file Plugins/HockeyAppUnityAndroid/HockeyAppUnity-Scripts/HockeyAppAndroid.cs

**Comment by chrwend** [comment]
Hi Bikush,

thanks for reporting. While the example game was up to date already, those changes were missing in the plugin folder. It's fixed now.

Thank you,

Christoph
