### ISSUE TITLE
Hockey statistic does not sync every crash and detection of crash 

### ISSUE THREAD

**Issue by DiegoHuang** [bitstadium/HockeySDK-Unity-Android#8]
Hi, 
I integrated hockey in Unity project (unity version 5.2.0 and running on device android version 5.0.2).  I'm getting two problems as following: 

1. Hockey can not detect crash(not exception log) on my app, it does not prompt message "The app found information about previous crash. Would you like to send this data to developer?" after crashing like ExampleGame, and I'm sure that "Auto Upload" option are disabled both. Is there any reason cause this problem? 

2. When crash or exception happens, statistic does not really sync crashes field everytime. Sometimes worked, but sometimes broken. And I also analysis packets with Packet Capture, it seemed to send packets to hockeyApp service correctly. 

Thank you.

**Comment by DiegoHuang** [comment]
Hi, 
I'm getting new progresses in first problem now. When crash happened with "Fatal signal 5 (SIGTRAP), code -6 in tid 7072 (UnityMain)" message that was printed on LogCat Device Monitor, that crash would not be recorded as .stacktrace file (or even not be probed?), so that hockey cannot find crash report files in "/data/data/[packageID]/files/" folder and show confirm message of previous crash report next time.

**Comment by chrwend** [comment]
Hi,

let's start with problem one. Can you please use the example app to verify, that unhandled exceptions from Android code are send correctly?

Chris
